export const ACTION = {
    'IMPORT_TUNEBOOK':'getTuneBookFromImportedFile',
    'LOAD_EXAMPLE_TUNEBOOK':'getExampleTuneBookFromServer',
    'INITIALIZE_TUNEBOOK':'initializeTuneBook',
    'EDIT_TUNEBOOK_NAME':'handleBlurOnTuneBookName',
    'EDIT_TUNEBOOK_VERSION':'handleBlurOnTuneBookVersion',
    'EDIT_TUNEBOOK_DESCRIPTION':'handleBlurOnTuneBookDescription',
    'ADD_TUNESET':'addTuneSet',
    'ADD_VIDEO':'addVideo',
    'ADD_WEBSITE':'addWebsite',
    'DELETE_TUNE':'deleteTune',
    'DELETE_TUNESETPOSITION': 'deleteTuneSetPosition',
    'DELETE_PLAYLISTPOSITION': 'deletePlaylistPosition',
    'ADD_SETS_TO_PLAYLIST':'addPlaylistPositions',
    'APPLY_FILTER':'applyFilter',
    'TOGGLE_EDIT_MODUS':'toggleEditModus',
    'TOGGLE_SHOW_PLAYLIST_DOTS':'toggleShowPlaylistDots',
    'CHANGE_NUMBER_OF_BARS_OF_PLAYLIST_DOTS':'changeNumberOfBarsOfPlaylistDots',
    'IS_RENDERING':'isRendering',
    'IS_RENDERED':'isRendered'
};
